dtb-$(CONFIG_ARCH_FSL_IMX8MM) += imx8mm-cgtsx8m.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += imx8mm-cgtsx8m-1024x768.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += imx8mm-cgtsx8m-1280x1024_experimental.dtb 
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += imx8mm-cgtsx8m-1440x900_experimental.dtb 
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += imx8mm-cgtsx8m-1280x1024_G170EG01.dtb     
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += imx8mm-cgtsx8m-640x480.dtb        
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += imx8mm-cgtsx8m-1280x720_default.dtb       
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += imx8mm-cgtsx8m-800x600.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb

