dtb-$(CONFIG_ARCH_MXC) += imx8mm-cgtsx8m.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mm-cgtsx8m-dp.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mm-cgtsx8m-dp-1280x1024.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mm-cgtsx8m-800x600.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mm-cgtsx8m-1024x768-JEIDA.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mm-cgtsx8m-1920x1080-2ch.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
