# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8qm-cgtsmx8.dtb \
							imx8qm-cgtsmx8-rpmsg.dtb \
							imx8qm-cgtsmx8-pcieb.dtb \
							imx8qm-cgtsmx8-hdmi.dtb \
							imx8qm-cgtsmx8-hdmi-pcieb.dtb \
							imx8qm-cgtsmx8-edp.dtb \

